// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC2u_2_yR4qupC9G2USLt_tCAE2SEtFDGY',
    appId: '1:803402655691:android:adb01b443b0a5ef1db784e',
    messagingSenderId: '803402655691',
    projectId: 'lmtnaapplication',
    storageBucket: 'lmtnaapplication.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyClK0YvJ1Re6L326lSc_cYb3ftA9mrdPc4',
    appId: '1:803402655691:ios:b125cab0064d3047db784e',
    messagingSenderId: '803402655691',
    projectId: 'lmtnaapplication',
    storageBucket: 'lmtnaapplication.firebasestorage.app',
    iosClientId:
        '803402655691-rvodm29b44rvf3q03mruni8au7fc978h.apps.googleusercontent.com',
    iosBundleId: 'com.example.newStrucuture',
  );
  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBCHNpvTFsyJT9MM5tytD4vh03w0SavzME',
    appId: '1:803402655691:web:c0f32795978a5877db784e',
    messagingSenderId: '803402655691',
    projectId: 'lmtnaapplication',
    authDomain: 'lmtnaapplication.firebaseapp.com',
    storageBucket: 'lmtnaapplication.firebasestorage.app',
    measurementId: 'G-E9MZWB7TP4',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyClK0YvJ1Re6L326lSc_cYb3ftA9mrdPc4',
    appId: '1:803402655691:ios:b125cab0064d3047db784e',
    messagingSenderId: '803402655691',
    projectId: 'lmtnaapplication',
    storageBucket: 'lmtnaapplication.firebasestorage.app',
    iosClientId:
        '803402655691-rvodm29b44rvf3q03mruni8au7fc978h.apps.googleusercontent.com',
    iosBundleId: 'com.example.newStrucuture',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBCHNpvTFsyJT9MM5tytD4vh03w0SavzME',
    appId: '1:803402655691:web:74b5fa1c6b2dd8d1db784e',
    messagingSenderId: '803402655691',
    projectId: 'lmtnaapplication',
    authDomain: 'lmtnaapplication.firebaseapp.com',
    storageBucket: 'lmtnaapplication.firebasestorage.app',
    measurementId: 'G-WPLHDM5QGD',
  );
}
